Clean up old mount-control host-hunspell in post-refresh too
This is a temporary measure likely needed only for the users of
'nightly' and 'beta' who had their Firefox snap updated and the
old host-hunspell mount-control plug disconnected without proper
unmounting and cleanup of the mount point.

diff --git a/snap/hooks/post-refresh b/snap/hooks/post-refresh
--- a/snap/hooks/post-refresh
+++ b/snap/hooks/post-refresh
@@ -14,6 +14,15 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+if [ -d $SNAP_COMMON/host-hunspell ]; then
+    # Clean up old Firefox snap mount for host hunspell; we now use
+    # the system-files interface for host hunspell dictionaries.
+    # See the 'disconnect-plug-host-hunspell' hook for more details.
+    snapctl umount $SNAP_COMMON/host-hunspell || true
+    rm -r $SNAP_COMMON/host-hunspell || true
+    exit 0
+fi
+
 host_hunspell=/var/lib/snapd/hostfs/usr/share/hunspell
 
 if [ ! -d  $host_hunspell ]; then
